### ISSUE TITLE
Renaming instructions are confusing

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/player-space#1]
Two new players have renamed the README.md file instead of changing the name within the file.

**Comment by Flaxscrip** [comment]
We could add hidden comments in the README.md with specific instructions.

There seems to be 2 ways to do it:  https://alvinalexander.com/technology/markdown-comments-syntax-not-in-generated-output 

I just tested it and both work with Github's markdown engine and pages: https://flaxscrip.github.io/flaxscrip-space/
