### ISSUE TITLE
New Rules Suggestions

### ISSUE THREAD

**Issue by joestartupsocieties** [cryptotechguru/player-space#3]
I suggest creating two rules new rules to govern finances for the Ulex Open Source Community.

Rule #4: 10% of all bounties must go to the Ulex Open Source Community Fund for management expenses.
Rule #5: The budgeting of the Ulex Open Source Community Fund will be governed similar to Tom W Bell's [double democracy](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2622627). The Ulex Advisory Board proposes a budget and discloses meeting meeting minutes to the community. Users have the ability to veto the proposed budget with a 3/4 majority.

**Comment by macterra** [comment]
I took the liberty of moving this issue to https://github.com/cryptotechguru/Lexinomicon/issues/15
